name: Build Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GODOT_VERSION: 4.5.1
  EXPORT_NAME: ZombieBox
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1 # Fixes missing ICU package on Linux runners

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build C# Solution
        run: dotnet build -c ExportRelease

      - name: Install Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.5.1.stable.mono
          wget https://github.com/godotengine/godot/releases/download/4.5.1-stable/Godot_v4.5.1-stable_mono_export_templates.tpz
          unzip Godot_v4.5.1-stable_mono_export_templates.tpz
          mv templates/* ~/.local/share/godot/export_templates/4.5.1.stable.mono/
          rm -f Godot_v4.5.1-stable_mono_export_templates.tpz

      - name: Create Build Directory
        run: mkdir -v -p build/windows

      - name: Export Windows
        run: godot --headless --export-release "Windows Desktop" build/windows/$EXPORT_NAME.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows

  export-macos:
    name: macOS Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build C# Solution
        run: dotnet build -c ExportRelease

      - name: Install Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.5.1.stable.mono
          wget https://github.com/godotengine/godot/releases/download/4.5.1-stable/Godot_v4.5.1-stable_mono_export_templates.tpz
          unzip Godot_v4.5.1-stable_mono_export_templates.tpz
          mv templates/* ~/.local/share/godot/export_templates/4.5.1.stable.mono/
          rm -f Godot_v4.5.1-stable_mono_export_templates.tpz

      - name: Create Build Directory
        run: mkdir -v -p build/macos

      - name: Export macOS
        run: godot --headless --export-release "macOS" build/macos/$EXPORT_NAME.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/macos